### ISSUE TITLE
NAMESPACE (still) references future::multiprocess

### ISSUE THREAD

**Issue by HenrikBengtsson** [xiaodaigh/disk.frame#397]
Hello again (#394).  Unfortunately, <https://cran.r-project.org/web/packages/disk.frame/NAMESPACE> still contains:

```
importFrom(future,multiprocess)
```

meaning the package will fail checks with the next release of **future**.

**Comment by HenrikBengtsson** [comment]
Closing. Appears to have been resolved, cf. <https://cran.r-project.org/web/packages/disk.frame/news/news.html>.

**Comment by HenrikBengtsson** [comment]
I was too quick.  Revdep checks show that complain, and, yes, https://cran.r-project.org/web/packages/disk.frame/NAMESPACE still contains:

```
importFrom(future,multiprocess)
```

I will submit an updated version of **future** very very soon to CRAN and your package will break because of this.

**Comment by xiaodaigh** [comment]
ok. I am looking into this now. the latest version should fix this

**Comment by xiaodaigh** [comment]
ah cran is of until 7 Aug

**Comment by jiversivers** [comment]
Just installed fresh everything and updated; still getting this error. 
`Error: package or namespace load failed for 'disk.frame': `
` object 'multiprocess' is not exported by 'namespace:future'`

**Comment by yangchuhua** [comment]
I got the same error report, and I installed by Conda.
```
library(disk.frame)
Error: package or namespace load failed for ‘disk.frame’:
 object ‘multiprocess’ is not exported by 'namespace:future'
```

**Comment by xiaodaigh** [comment]
I will try to submit to cran again.

**Comment by xiaodaigh** [comment]
0.8.3going to CRAN soon. so hopefully it's fixed for good!
